name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Assuming 'configure-pages' is used to configure GitHub Pages settings
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Upload the 'plugins' directory as an artifact
      - name: Upload plugins artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: plugins

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Path within the artifact to deploy
          path: plugins
